---
spec/spec_helper.rb:
  spec_overrides:
    - require 'spec_helper_local'
  mock_with: ':rspec'
  coverage_report: true
  minimum_code_coverage_percentage: 95
Gemfile:
  optional:
    ":development":
      - gem: 'github_changelog_generator'
        git: 'https://github.com/github-changelog-generator/github-changelog-generator'
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.travis.yml:
  delete: true
